### ISSUE TITLE
Crash when a deamon was killed

### ISSUE THREAD

**Issue by sblondon** [arthur-hav/hexrl#2]
When the daemon dies (in 3rd level), the game crashed. The output in console is:

```
$ ./venv/bin/python worldmap.py 
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "worldmap.py", line 244, in <module>
    DISPLAY.main()
  File "/home/stephane/src/hexrl/display.py", line 65, in main
    handler(pos)
  File "/home/stephane/src/hexrl/game.py", line 172, in on_click
    self.done()
  File "/home/stephane/src/hexrl/display.py", line 243, in done
    self.father.on_return(self)
  File "/home/stephane/src/hexrl/game.py", line 662, in on_return
    self.game.apply_ability(defunct.ability, self.game.to_act, defunct.target)
  File "/home/stephane/src/hexrl/game.py", line 489, in apply_ability
    self.new_turn()
  File "/home/stephane/src/hexrl/game.py", line 502, in new_turn
    creature.tick(elapsed_time)
  File "/home/stephane/src/hexrl/creatures.py", line 118, in tick
    self.status[i].status_end(self)
  File "/home/stephane/src/hexrl/status.py", line 34, in status_end
    creature.rooted.remove(self)
ValueError: list.remove(x): x not in list
```

**Comment by arthur-hav** [comment]
I suspect the root status effect was somehow removed twice because the monster died and because its effect ended. I will investigate the matter.

**Comment by arthur-hav** [comment]
[This commit](https://github.com/arthur-hav/hexrl/commit/e8800969f6338b3044fe28c760e14568b96742d6)

Should fix the issue.
