### ISSUE TITLE
Crash when talking in the tavern

### ISSUE THREAD

**Issue by sblondon** [arthur-hav/hexrl#4]
When I execute the game, choose 'slot 1', choose 'ask', the game crashes at the first keystoke (for example with the 'a' key).

```$ make play
./venv/bin/python main.py
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    DISPLAY.main()
  File "/home/stephane/src/hexrl/display.py", line 70, in main
    handler(event.unicode)
  File "/home/stephane/src/hexrl/choices.py", line 341, in typing
    self.word += code7
NameError: name 'code7' is not defined
make: *** [Makefile:6: play] Error 1
```

**Comment by arthur-hav** [comment]
That one was easy, i had randomly inserted a 7 in the code.
It's fixed now
