### ISSUE TITLE
Error after buying an item

### ISSUE THREAD

**Issue by sblondon** [arthur-hav/hexrl#6]
After trading a HealthPotion for 9 gold, an error is raised and the game exits:

```
$ make play 
./venv/bin/python main.py
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    DISPLAY.main()
  File "/home/stephane/src/hexrl/display.py", line 79, in main
    handler(pos)
  File "/home/stephane/src/hexrl/worldmap.py", line 209, in update
    self.inventory_display.update(mouse_pos)
  File "/home/stephane/src/hexrl/worldmap.py", line 111, in update
    if item.equipped_to:
AttributeError: 'HealthPotion' object has no attribute 'equipped_to'
make: *** [Makefile:6: play] Error 1
```

**Comment by arthur-hav** [comment]
This problem is now solved.
